<div id="assignments">
	<a href="http://helios.vse.gmu.edu/~agarciar/IT207/">Home</a>
		<p><b>Lab Assignments</b></p>
		<div id="sidenav">
			<div id="lab-assignments">
			<ul>
				<li><a href="http://helios.vse.gmu.edu/~agarciar/IT207/Lab1/">Assignment 1</a></li>
				<li><a href="http://helios.vse.gmu.edu/~agarciar/IT207/Lab2/">Assignment 2</a></li>
				<li><a href="http://helios.vse.gmu.edu/~agarciar/IT207/Lab3/">Assignment 3</a></li>
				<li><a href="http://helios.vse.gmu.edu/~agarciar/IT207/Lab4/">Assignment 4</a></li>
			</ul>
			</div>
			<p><b>Lab Practica</b></p>
			<div id="lab-practica">
			<ul>
				<li><a href="http://helios.vse.gmu.edu/~agarciar/IT207/Practicum1/">Practicum 1</a></li>
				<li><a href="http://helios.vse.gmu.edu/~agarciar/IT207/Practicum2/">Practicum 2</a></li>
			</ul>	
			</div>
		</div>
</div>